import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import ThemeContext from "@/contexts/ThemeContext";

const nunito = Lato({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <ThemeContext>
        <body className={nunito.className}>{children}</body>
      </ThemeContext>
    </html>
  );
}
